# Site
name: 'The Flair'
description: 'Here at The Flair we inspire and endeavor to share everything about technology like Softwares, Coding, etc., and provide our best about HOW TO tutorials and BEST OF every category in accordence to our knowledge.'


logo: 'assets/images/clogo.png'
favicon: 'assets/images/favicon.png'
baseurl: '/mundana-theme-jekyll'
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      short_name:     sal
      name:           Sal
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    jane:
      short_name:     jane
      name:           Jane
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    puneeth:
      short_name:     puneeth
      name:           Neerukonda Puneeth
      site:           https://puneethkanna.github.io
      avatar:         /assets/images/puneeth.jpg
      bio:            "Student Developer, Tech Enthusiastic, love to browse the Internet!"
      email:          neerukondapuneeth@gmail.com
      twitter:        https://twitter.com/puneeth_kanna
      
    nikhil:
      short_name:     nikhil
      name:           Nikhil Reddy Pyreddy
      site:           https://nikhilpyreddy.me/
      avatar:         /assets/images/nikhil.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/puneeth_kanna
    output: true
# Defaults
defaults:

  # all posts
  - scope:
      path: "/_posts"
      type: "posts"
    values:
      layout: post

      
  # all pages
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
